project:
  type: website
  output-dir: docs
  

website:
  title: "Ahmed T. Hammad"
  image: me.jpg
  navbar:
    left:
      - href: index.qmd
        text: "‚ÑπÔ∏è About"
      - teaching.qmd
      - research.qmd
      - students.qmd
      - papers.qmd
      - solutions.qmd
      - toolkits.qmd
      - text: "üìÉ CV"
        href: cv/cv.qmd
      - posts.qmd # add your posts.qmd file to your navbar!
      - slides.qmd 
    # your social media handles
      - gallery.qmd
    right:
      - icon: github
        text: Github
        href: https://github.com/athammad
      - icon: linkedin
        text: LinkedIn
        href: https://www.linkedin.com/in/ahmedt-h/
      - icon: envelope
        text: Email
        href: "mailto:ahmed.t.hammad@gmail.com"  
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full
    grid:
      body-width: 950px

editor: visual

